description = "Tiny base image (bionic build image, distroless-like run image) with buildpacks for Java, Java Native Image and Go"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/go:4.0.2"
  version = "4.0.2"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/java-native-image:7.44.2"
  version = "7.44.2"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/java:8.6.0"
  version = "8.6.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/procfile:5.5.0"
  version = "5.5.0"

[lifecycle]
  version = "0.15.3"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java-native-image"
    version = "7.44.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "8.6.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go"
    version = "4.0.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.5.0"

[stack]
  build-image = "docker.io/paketobuildpacks/build:1.3.104-tiny-cnb"
  id = "io.paketo.stacks.tiny"
  run-image = "index.docker.io/paketobuildpacks/run:tiny-cnb"
  run-image-mirrors = ["gcr.io/paketo-buildpacks/run:tiny-cnb"]
