description = "Tiny base image (bionic build image, distroless-like run image) with buildpacks for Java, Java Native Image and Go"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/go:3.1.0"
  version = "3.1.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/java-native-image:7.38.0"
  version = "7.38.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/java:7.11.0"
  version = "7.11.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/procfile:5.4.0"
  version = "5.4.0"

[lifecycle]
  version = "0.15.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java-native-image"
    version = "7.38.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "7.11.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go"
    version = "3.1.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.4.0"

[stack]
  build-image = "docker.io/paketobuildpacks/build:1.3.87-tiny-cnb"
  id = "io.paketo.stacks.tiny"
  run-image = "index.docker.io/paketobuildpacks/run:tiny-cnb"
  run-image-mirrors = ["gcr.io/paketo-buildpacks/run:tiny-cnb"]
