description = "Tiny base image (bionic build image, distroless-like run image) with buildpacks for Java, Java Native Image and Go"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/go:0.15.0"
  version = "0.15.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/java-native-image:7.13.0"
  version = "7.13.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/java:6.13.0"
  version = "6.13.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/procfile:5.1.0"
  version = "5.1.0"

[lifecycle]
  version = "0.13.3"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java-native-image"
    version = "7.13.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "6.13.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go"
    version = "0.15.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.1.0"

[stack]
  build-image = "docker.io/paketobuildpacks/build:1.3.28-tiny-cnb"
  id = "io.paketo.stacks.tiny"
  run-image = "index.docker.io/paketobuildpacks/run:tiny-cnb"
  run-image-mirrors = ["gcr.io/paketo-buildpacks/run:tiny-cnb"]
