description = "Tiny base image (bionic build image, distroless-like run image) with buildpacks for Java Native Image and Go"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/go:0.6.0"
  version = "0.6.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/java-native-image:5.3.0"
  version = "5.3.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/procfile:4.1.0"
  version = "4.1.0"

[lifecycle]
  version = "0.11.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java-native-image"
    version = "5.3.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go"
    version = "0.6.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "4.1.0"

[stack]
  build-image = "docker.io/paketobuildpacks/build:1.2.6-tiny-cnb"
  id = "io.paketo.stacks.tiny"
  run-image = "index.docker.io/paketobuildpacks/run:tiny-cnb"
  run-image-mirrors = ["gcr.io/paketo-buildpacks/run:tiny-cnb"]
