description = "Tiny base image (bionic build image, distroless-like run image) with buildpacks for Java Native Image and Go"

[[buildpacks]]
  image = "gcr.io/paketo-buildpacks/go:0.2.8"
  version = "0.2.8"

[[buildpacks]]
  image = "gcr.io/paketo-buildpacks/java-native-image:4.5.0"
  version = "4.5.0"

[lifecycle]
  version = "0.9.3"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java-native-image"
    version = "4.5.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go"
    version = "0.2.8"

[stack]
  id = "io.paketo.stacks.tiny"
  build-image = "docker.io/paketobuildpacks/build:1.0.10-tiny-cnb"
  run-image = "index.docker.io/paketobuildpacks/run:tiny-cnb"
  run-image-mirrors = ["gcr.io/paketo-buildpacks/run:tiny-cnb"]
